# NumPy Exercises
due to Petr Romov

In [1]:
import numpy as np

SELF. Generate a matrix with 1000 rows and 50 columns, elements being drawn from normal distribution $\mathcal{N}(1, 10)$. Specify random seed to make the result reproducible. Use http://docs.scipy.org/doc/numpy/reference/routines.random.html

In [9]:
np.random.seed(42)
data = np.random.normal(1, 10, size=(1000, 50))

SELF. Normalize the matrix: subtract from each column its mean and divide by the standard deviation. I suggest np.mean, np.std with axis parameter.

In [10]:
data -= data.mean(axis=0)
data /= data.std(axis=0)

Print for the following matrix row numbers for those rows, where element sum is greater than 10. I suggest np.sum and np.nonzero

In [17]:
(data.sum(axis=1) > 10).nonzero()[0]

array([ 17,  20,  22,  28,  29,  32,  34,  46,  54,  66,  73, 119, 121,
       159, 163, 173, 182, 230, 244, 261, 270, 273, 276, 284, 292, 299,
       304, 316, 324, 329, 346, 350, 354, 362, 396, 421, 432, 438, 450,
       451, 457, 468, 469, 491, 511, 520, 526, 529, 535, 538, 555, 572,
       583, 597, 603, 611, 612, 617, 623, 648, 665, 769, 777, 782, 793,
       796, 797, 799, 808, 809, 832, 839, 844, 850, 871, 880, 887, 888,
       901, 907, 916, 930, 940, 952, 957, 962, 974, 980, 991, 998])

SELF Compute averages in a sliding window over an array. Use np.cumsum
```
[1,2,3,4], window_size=2 -> [1.5, 2.5, 3.5]
```

In [25]:
# Author: Jaime Fernández del Río
# https://github.com/rougier/numpy-100/blob/master/100%20Numpy%20exercises.ipynb
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.  15.
  16.  17.  18.]


SELF Given a 1D array `a` return a 1D array `b` consisting of elements of a with `n` zeros insered between each consequent pair. Use np.zeros and indexing.
```
[1,2,3,4], n=2 -> [1, 0, 0, 2, 0, 0, 3, 0, 0, 4]
```

In [35]:
a = np.arange(1, 10)
n = 2
insertions_count = len(a) - 1
b = np.zeros(shape=len(a) + insertions_count * n, dtype=a.dtype)
b[::n+1] = a
print(a)
print(b)

[1 2 3 4 5 6 7 8 9]
[1 0 0 2 0 0 3 0 0 4 0 0 5 0 0 6 0 0 7 0 0 8 0 0 9]


SELF Given a NxM matrix of dtype=np.int, extract rows where not all values are equal
```
[[1,1,1],
 [2,1,1],
 [10,10,11],
 [2,2,2]]
->
[[2,1,1],
 [10,10,11]]
```

In [39]:
# Author: Robert Kern
# https://github.com/rougier/numpy-100/blob/master/100%20Numpy%20exercises.ipynb
Z = np.random.randint(0,2,(10,3))
print(Z)
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 1 0]
 [1 0 0]
 [1 1 0]
 [1 0 1]
 [1 0 1]
 [0 0 0]
 [0 0 1]]
[[0 0 1]
 [0 1 0]
 [1 1 0]
 [1 0 0]
 [1 1 0]
 [1 0 1]
 [1 0 1]
 [0 0 1]]
