# Numpy
A library for matrix computation. Tutorial credit to http://wiki.scipy.org/Tentative_NumPy_Tutorial

In [2]:
import numpy as np

NumPy's main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In Numpy dimensions are called axes. The number of axes is rank.

For example, the coordinates of a point in 3D space [1, 2, 1] is an array of rank 1, because it has one axis. That axis has a length of 3. In example pictured below, the array has rank 2 (it is 2-dimensional). The first dimension (axis) has a length of 2, the second dimension has a length of 3. 

In [3]:
np.array([[1, 0, 3], [0, 1, 2]])

array([[1, 0, 3],
       [0, 1, 2]])

Numpy's array class is called ndarray. It is also known by the alias array. Note that numpy.array is not the same as the Standard Python Library class array.array, which only handles one-dimensional arrays and offers less functionality. The more important attributes of an ndarray object are:

ndarray.ndim
 * the number of axes (dimensions) of the array. In the Python world, the number of dimensions is referred to as rank. 
    
ndarray.shape
 * the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the rank, or number of dimensions, ndim. 

ndarray.size
  * the total number of elements of the array. This is equal to the product of the elements of shape. 

ndarray.dtype
 * an object describing the type of the elements in the array. One can create or specify dtype's using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples. 
 
ndarray.itemsize
 * the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize. 

ndarray.data
 * the buffer containing the actual elements of the array. Normally, we won't need to use this attribute because we will access the elements in an array using indexing facilities. 

## Array Creation

There are several ways to create arrays.

For example, you can create an array from a regular Python list or tuple using the array function. The type of the resulting array is deduced from the type of the elements in the sequences. 

In [4]:
a = np.array((1, 2, 53))
a

array([ 1,  2, 53])

In [5]:
a.dtype

dtype('int64')

In [6]:
np.array([0.43, 03.4]).dtype

dtype('float64')

array transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.

In [7]:
np.array([(1.5, 2, 3), (4, 5, 6)])

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

The type of the array can also be explicitly specified at creation time. Also note handling of complex.

In [8]:
np.array([[1, 2], [3, 4]], dtype=complex)

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation.

The function zeros creates an array full of zeros, the function ones creates an array full of ones, and the function empty creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is float64. 

In [9]:
print(np.ones(3))
print(np.zeros(2))
print(np.empty([2, 2]))

[ 1.  1.  1.]
[ 0.  0.]
[[ 0.  0.]
 [ 0.  0.]]


To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists 

In [10]:
print(np.linspace(0, 1, num=4))
print(np.arange(0, 1, step=0.3))

[ 0.          0.33333333  0.66666667  1.        ]
[ 0.   0.3  0.6  0.9]


# IO

In [31]:
example_file = "../../DS_1_electron_train.csv"
electrons = np.genfromtxt(example_file, delimiter=",", names=True)

In [32]:
electrons.dtype

dtype([('index', '<f8'), ('event_id', '<f8'), ('P', '<f8'), ('X', '<f8'), ('Y', '<f8'), ('Z', '<f8'), ('TX', '<f8'), ('TY', '<f8')])

In [33]:
electrons['index']

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
        99.])

In [35]:
# This fails
# electrons[0, 0]

In [36]:
electrons = np.genfromtxt(example_file, delimiter=",", skip_header=1, names=None)

In [37]:
electrons[0, 0]

0.0

In [38]:
np.savetxt("test.csv", np.random.random(size=(10, 10)), delimiter=',')

In [39]:
! head -n 1 test.csv

6.271145760644855072e-01,2.479183849181969546e-01,1.579089747031899860e-01,1.340025285506640795e-01,6.037888049437735161e-01,7.449035248861064495e-01,5.978605341570152332e-01,2.614384154726325793e-01,2.517972104108566755e-01,6.650342681127774380e-01


## Basic Operations
Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result. Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

In [15]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
print(a, b)
print(a-b)
print(b**2)
print(a > 32)
a += 1
print(a)

[20 30 40 50] [0 1 2 3]
[20 29 38 47]
[0 1 4 9]
[False False  True  True]
[21 31 41 51]


Unlike in many matrix languages, the product operator * operates elementwise in NumPy arrays. The matrix product can be performed using the dot function or creating matrix objects. 

In [16]:
A = np.array([[1,1], [0,1]])
B = np.array([[2,0], [3,4]])
print(A * B)
print(np.dot(A, B))

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one (a behavior known as upcasting). 

In [17]:
a = np.ones(3, dtype=np.int)
b = np.linspace(0, np.pi, 3)
print(a.dtype, b.dtype, (a + b).dtype)

int64 float64 float64


Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the ndarray class.

In [18]:
a = np.random.random((2,3))
print(a)
print(a.sum(), a.min(), a.max())

[[ 0.58735141  0.58652936  0.88756913]
 [ 0.54295559  0.64247796  0.23736038]]
3.48424381916 0.237360375513 0.88756912618


By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. However, by specifying the axis parameter you can apply an operation along the specified axis of an array: 

In [19]:
b = np.arange(12).reshape(3,4)
print(b)
print(b.sum(axis=0))
print(b.sum(axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[ 6 22 38]


## Universal Functions

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called "universal functions" (ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output. 

In [20]:
np.sqrt(np.arange(0, 10))

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

## Indexing, Slicing and Iterating

One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences. Format [start:stop:step]

In [21]:
a = np.arange(10)**2
print(a)

[ 0  1  4  9 16 25 36 49 64 81]


In [22]:
a[2]

4

In [23]:
a[3:100]

array([ 9, 16, 25, 36, 49, 64, 81])

In [24]:
a[::-1]

array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0])

In [25]:
a[::2]

array([ 0,  4, 16, 36, 64])

Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas: 

In [26]:
def f(x,y):
    return 10*x+y
b = np.fromfunction(f, (5, 4), dtype=int)
print(b)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]


In [27]:
b[2,3]

23

Each row in the second column of b

In [28]:
b[0:5, 1]                       

array([ 1, 11, 21, 31, 41])

Equivalent to the previous example

In [29]:
b[ : ,1]

array([ 1, 11, 21, 31, 41])

Each column in the second and third row of b

In [30]:
b[1:3, : ]                      

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

When fewer indices are provided than the number of axes, the missing indices are considered complete slices. The expression within brackets in b[i] is treated as an i followed by as many instances of : as needed to represent the remaining axes. NumPy also allows you to write this using dots as b[i,...].

The dots (...) represent as many colons as needed to produce a complete indexing tuple. For example, if x is a rank 5 array (i.e., it has 5 axes), then

    x[1,2,...] is equivalent to x[1,2,:,:,:],

    x[...,3] to x[:,:,:,:,3] and

    x[4,...,5,:] to x[4,:,:,5,:]. 

In [31]:
b[-1]

array([40, 41, 42, 43])

Iterating over multidimensional arrays is done with respect to the first axis:

In [32]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


However, if one wants to perform an operation on each element in the array, one can use the flat attribute which is an iterator over all the elements of the array:

In [33]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


## Shape Manipulation
Changing the shape of an array. An array has a shape given by the number of elements along each axis: 

In [34]:
a = np.floor(10*np.random.random((3,4)))
print(a, a.shape)

[[ 5.  2.  2.  6.]
 [ 8.  5.  0.  3.]
 [ 8.  5.  7.  6.]] (3, 4)


The shape of an array can be changed with various commands: 

In [35]:
print(a.ravel())
print(a.transpose())

[ 5.  2.  2.  6.  8.  5.  0.  3.  8.  5.  7.  6.]
[[ 5.  8.  8.]
 [ 2.  5.  5.]
 [ 2.  0.  7.]
 [ 6.  3.  6.]]


The order of the elements in the array resulting from ravel() is normally "C-style", that is, the rightmost index "changes the fastest", so the element after a[0,0] is a[0,1]. If the array is reshaped to some other shape, again the array is treated as "C-style". Numpy normally creates arrays stored in this order, so ravel() will usually not need to copy its argument, but if the array was made by taking slices of another array or created with unusual options, it may need to be copied. The functions ravel() and reshape() can also be instructed, using an optional argument, to use FORTRAN-style arrays, in which the leftmost index changes the fastest.

The reshape function returns its argument with a modified shape, whereas the resize method modifies the array itself: 

In [36]:
print(a)
a.resize((2, 6))
print(a)

[[ 5.  2.  2.  6.]
 [ 8.  5.  0.  3.]
 [ 8.  5.  7.  6.]]
[[ 5.  2.  2.  6.  8.  5.]
 [ 0.  3.  8.  5.  7.  6.]]


If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated: 

In [37]:
a.reshape(3, -1)

array([[ 5.,  2.,  2.,  6.],
       [ 8.,  5.,  0.,  3.],
       [ 8.,  5.,  7.,  6.]])

## Stacking together different arrays

Several arrays can be stacked together along different axes:

In [38]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))
print(a)
print(b)

[[ 8.  1.]
 [ 3.  4.]]
[[ 1.  4.]
 [ 9.  0.]]


In [39]:
np.vstack((a, b))

array([[ 8.,  1.],
       [ 3.,  4.],
       [ 1.,  4.],
       [ 9.,  0.]])

In [40]:
np.hstack((a, b))

array([[ 8.,  1.,  1.,  4.],
       [ 3.,  4.,  9.,  0.]])

The function column_stack stacks 1D arrays as columns into a 2D array. It is equivalent to vstack only for 1D arrays: 

In [41]:
np.column_stack((a,b))  

array([[ 8.,  1.,  1.,  4.],
       [ 3.,  4.,  9.,  0.]])

In [42]:
b = np.array([2., 8.])
np.column_stack((a, b))

array([[ 8.,  1.,  2.],
       [ 3.,  4.,  8.]])

The function row_stack, on the other hand, stacks 1D arrays as rows into a 2D array.

For arrays of with more than two dimensions, hstack stacks along their second axes, vstack stacks along their first axes, and concatenate allows for an optional arguments giving the number of the axis along which the concatenation should happen.

## Splitting one array into several smaller ones

In [43]:
a = np.floor(10*np.random.random((2,12)))
a

array([[ 8.,  4.,  7.,  7.,  3.,  9.,  0.,  4.,  6.,  9.,  3.,  0.],
       [ 2.,  3.,  9.,  4.,  9.,  0.,  0.,  7.,  1.,  9.,  7.,  9.]])

Split a into 3

In [44]:
np.hsplit(a, 3)

[array([[ 8.,  4.,  7.,  7.],
        [ 2.,  3.,  9.,  4.]]), array([[ 3.,  9.,  0.,  4.],
        [ 9.,  0.,  0.,  7.]]), array([[ 6.,  9.,  3.,  0.],
        [ 1.,  9.,  7.,  9.]])]

Split a after the third and the fourth column

In [45]:
np.hsplit(a, (3, 4))

[array([[ 8.,  4.,  7.],
        [ 2.,  3.,  9.]]), array([[ 7.],
        [ 4.]]), array([[ 3.,  9.,  0.,  4.,  6.,  9.,  3.,  0.],
        [ 9.,  0.,  0.,  7.,  1.,  9.,  7.,  9.]])]

## Copies and Views or how to shoot yourself in a foot

When operating and manipulating arrays, their data is sometimes copied into a new array and sometimes not. This is often a source of confusion for beginners. There are three cases:
### No Copy at All

In [46]:
a = np.arange(12)
b = a
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [47]:
b[0] = -100
b

array([-100,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11])

In [48]:
a

array([-100,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11])

### View or Shallow Copy

Different array objects can share the same data. The view method creates a new array object that looks at the same data. 

In [49]:
c = a.view()

In [50]:
c.resize((2, 6))
c

array([[-100,    1,    2,    3,    4,    5],
       [   6,    7,    8,    9,   10,   11]])

In [51]:
a

array([-100,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11])

In [52]:
a[0] = 123

In [53]:
c

array([[123,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11]])

Slicing an array returns a view of it.

In [54]:
s = c[ : , 1:3]  

In [55]:
s[:] = 10

In [56]:
c

array([[123,  10,  10,   3,   4,   5],
       [  6,  10,  10,   9,  10,  11]])

### Deep Copy

The copy method makes a complete copy of the array and its data. 

In [57]:
d = a.copy()        

In [58]:
d[0] = -42
d

array([-42,  10,  10,   3,   4,   5,   6,  10,  10,   9,  10,  11])

In [59]:
a

array([123,  10,  10,   3,   4,   5,   6,  10,  10,   9,  10,  11])

Rules of thumb:
1. Explicitly use `copy` if you need a copy
2. Avoid situations where you need mutable non-trivial views. If you must, read documentation

## Broadcasting rules (know what you are doing)

**Broadcasting allows universal functions to deal in a meaningful way with inputs that do not have exactly the same shape.**

1. The first rule of broadcasting is that if all input arrays do not have the same number of dimensions, a "1" will be repeatedly prepended to the shapes of the smaller arrays until all the arrays have the same number of dimensions.

2. The second rule of broadcasting ensures that arrays with a size of 1 along a particular dimension act as if they had the size of the array with the largest shape along that dimension. The value of the array element is assumed to be the same along that dimension for the "broadcast" array.

After application of the broadcasting rules, the sizes of all arrays must match. More details can be found in this documentation. 

In [60]:
a = np.array([1,2,3])
b = np.ones(shape=(3,6))
print(a.shape, b.shape)
# This will fail
# a * b

(3,) (3, 6)


In [61]:
c = np.ones(shape=(6, 3))
print(a.shape, c.shape)
a * c

(3,) (6, 3)


array([[ 1.,  2.,  3.],
       [ 1.,  2.,  3.],
       [ 1.,  2.,  3.],
       [ 1.,  2.,  3.],
       [ 1.,  2.,  3.],
       [ 1.,  2.,  3.]])

## Fancy indexing and index tricks

NumPy offers more indexing facilities than regular Python sequences. In addition to indexing by integers and slices, as we saw before, arrays can be indexed by arrays of integers and arrays of booleans.
### Indexing with Arrays of Indices

In [62]:
a = np.arange(12)**2         
i = np.array([1, 1, 3, 8, 5])
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [63]:
a[i]

array([ 1,  1,  9, 64, 25])

A bidimensional array of indices

In [64]:
j = np.array([[ 3, 4], [9, 7]])

Note the same shape

In [65]:
a[j]

array([[ 9, 16],
       [81, 49]])

Also can have multidimensional both index and array - see [documentation](http://wiki.scipy.org/Tentative_NumPy_Tutorial#head-3f4d28139e045a442f78c5218c379af64c2c8c9e)
## Indexing with Boolean Arrays
When we index arrays with arrays of (integer) indices we are providing the list of indices to pick. With boolean indices the approach is different; we explicitly choose which items in the array we want and which ones we don't.

The most natural way one can think of for boolean indexing is to use boolean arrays that have the same shape as the original array:

In [66]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [68]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

The second way of indexing with booleans is more similar to integer indexing; for each dimension of the array we give a 1D boolean array selecting the slices we want. Note that the length of the 1D boolean array must coincide with the length of the dimension (or axis) you want to slice. In the following example, b1 is a 1-rank array with length 3 (the number of rows in a), and b2 (of length 4) is suitable to index the 2nd rank (columns) of a. 

In [69]:
a = np.arange(12).reshape(3,4)
b1 = np.array([False,True,True])             # first dim selection
b2 = np.array([True,False,True,False])       # second dim selection

In [70]:
a[b1, :] # rows

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [71]:
a[:, b2] # columns

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [72]:
a[b1, b2] # both

array([ 4, 10])