# Intro to numpy

This notebook's gonna teach you to play around with data using numpy, pandas and matplotlib.

Let's get started!

#### Jupyter primer:
* Those blocks below are cells. Click on cell to select. Ctrl+enter to run code from cell.
* Click topbar "+" button to create new cell.
* Sometimes we'll ask you to add `<your code here doing such and such things>`

In [1]:
#execute this cell

from __future__ import print_function

import math

In [ ]:
#type "math." or "math.s" and press tab
<here>

In [ ]:
#type math.atan2() and press shift+tab inside the brackets
<here>

In [ ]:
del math

#oops, i destroyed math :)

# Gettin' all vectorized with Numpy

In [60]:
import numpy as np

#numpy's main object is the homogeneous multidimensional array.
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])

print ("a = ",a)
print ("b = ",b)

a =  [1 2 3 4 5]
b =  [5 4 3 2 1]


In [61]:
#Arithmetic operators on arrays apply elementwise. 
print ("a+1 =", a+1)
print ("a*2 =", a*2)

#Or pairwise, etc.
print ("a+b =",a+b)
print ("a*b= ",a*b)
print ("a*b + b**a =",a*b + b**a)


a+1 = [2 3 4 5 6]
a*2 = [ 2  4  6  8 10]
a+b = [6 6 6 6 6]
a*b=  [5 8 9 8 5]
a*b + b**a = [10 24 36 24  6]


Numpy's also rich on functions that compute all kinds of stuff

In [4]:
print ("numpy.sum(a) = ",np.sum(a))
print ("numpy.mean(a) = ", np.mean(a))
print ("numpy.min(a) = ", np.min(a))
print ("numpy.argmax(a) = ", np.argmax(a)) #index of minimal element
print ("numpy.log(b) = ",np.log(b))
print ("numpy.arctan(b) = ",np.arctan(b))
print ("numpy.unique(['b','c','d','c','b']) = ",np.unique(['b','c','d','c','b']))


numpy.sum(a) =  15
numpy.mean(a) =  3.0
numpy.min(a) =  1
numpy.argmax(a) =  4
numpy.log(b) =  [ 1.60943791  1.38629436  1.09861229  0.69314718  0.        ]
numpy.arctan(b) =  [ 1.37340077  1.32581766  1.24904577  1.10714872  0.78539816]
numpy.unique(['b','c','d','c','b']) =  ['b' 'c' 'd']


### Wax on, wax off

In [7]:
#The basics of numpy
print ("Difference between a and b:", a-b)
print ("Sum of squares of a and b:", a**2+b**2)
print ("a minus 2 divided by square root of b", (a-2)/np.sqrt(b))

Difference between a and b: [-4 -2  0  2  4]
Sum of squares of a and b: [26 20 18 20 26]
a minus 2 divided by square root of b [-0.4472136   0.          0.57735027  1.41421356  3.        ]


In [8]:
print ("difference between minimum and maximum of a", min(a)-max(a))

difference between minimum and maximum of a -4


In [9]:
print ("mean squared error between a and b", np.mean((a-b)**2))

mean squared error between a and b 8.0


## Hello, data

In [10]:
import pandas as pd
data = pd.read_csv("small_higgs.csv",na_values=-999).fillna(0)

In [11]:
#Data's a table, 2d array. Here's first 10 elements.
data[:10]

EventId  DER_mass_MMC  DER_mass_transverse_met_lep  DER_mass_vis  DER_pt_h  \
0   100000       138.470                       51.655        97.827    27.980   
1   100001       160.937                       68.768       103.235    48.146   
2   100002         0.000                      162.172       125.953    35.635   
3   100003       143.905                       81.417        80.943     0.414   
4   100004       175.864                       16.915       134.805    16.405   
5   100005        89.744                       13.550        59.149   116.344   
6   100006       148.754                       28.862       107.782   106.130   
7   100007       154.916                       10.418        94.714    29.169   
8   100008       105.594                       50.559       100.989     4.288   
9   100009       128.053                       88.941        69.272   193.392   

   DER_deltaeta_jet_jet  DER_mass_jet_jet  DER_prodeta_jet_jet  \
0                 0.910           124.711                2.666   
1                 0.000             0.000                0.000   
2                 0.000             0.000                0.000   
3                 0.000             0.000                0.000   
4                 0.000             0.000                0.000   
5                 2.636           284.584               -0.540   
6                 0.733           158.359                0.113   
7                 0.000             0.000                0.000   
8                 0.000             0.000                0.000   
9                 0.000             0.000                0.000   

   DER_deltar_tau_lep  DER_pt_tot  ...    PRI_jet_num  PRI_jet_leading_pt  \
0               3.064      41.928  ...              2              67.435   
1               3.473       2.078  ...              1              46.226   
2               3.148       9.336  ...              1              44.251   
3               3.310       0.414  ...              0               0.000   
4               3.891      16.405  ...              0               0.000   
5               1.362      61.619  ...              3              90.547   
6               2.941       2.545  ...              2             123.010   
7               2.897       1.526  ...              1              30.638   
8               2.904       4.288  ...              0               0.000   
9               1.609      28.859  ...              1             167.735   

   PRI_jet_leading_eta  PRI_jet_leading_phi  PRI_jet_subleading_pt  \
0                2.150                0.444                 46.062   
1                0.725                1.158                  0.000   
2                2.053               -2.028                  0.000   
3                0.000                0.000                  0.000   
4                0.000                0.000                  0.000   
5               -2.412               -0.653                 56.165   
6                0.864                1.450                 56.867   
7               -0.715               -1.724                  0.000   
8                0.000                0.000                  0.000   
9               -2.767               -2.514                  0.000   

   PRI_jet_subleading_eta  PRI_jet_subleading_phi  PRI_jet_all_pt    Weight  \
0                   1.240                  -2.475         113.497  0.002653   
1                   0.000                   0.000          46.226  2.233584   
2                   0.000                   0.000          44.251  2.347389   
3                   0.000                   0.000          -0.000  5.446378   
4                   0.000                   0.000           0.000  6.245333   
5                   0.224                   3.106         193.660  0.083414   
6                   0.131                  -2.767         179.877  0.002653   
7                   0.000                   0.000          30.638  0.018636   
8                   0.000                   0.000     

In [12]:
#Data shapes
print ("len(data) = ",len(data))
print ("data.shape = ",data.shape)
print ("data.columns = ",data.columns)

len(data) =  4999
data.shape =  (4999, 33)
data.columns =  Index([u'EventId', u'DER_mass_MMC', u'DER_mass_transverse_met_lep',
       u'DER_mass_vis', u'DER_pt_h', u'DER_deltaeta_jet_jet',
       u'DER_mass_jet_jet', u'DER_prodeta_jet_jet', u'DER_deltar_tau_lep',
       u'DER_pt_tot', u'DER_sum_pt', u'DER_pt_ratio_lep_tau',
       u'DER_met_phi_centrality', u'DER_lep_eta_centrality', u'PRI_tau_pt',
       u'PRI_tau_eta', u'PRI_tau_phi', u'PRI_lep_pt', u'PRI_lep_eta',
       u'PRI_lep_phi', u'PRI_met', u'PRI_met_phi', u'PRI_met_sumet',
       u'PRI_jet_num', u'PRI_jet_leading_pt', u'PRI_jet_leading_eta',
       u'PRI_jet_leading_phi', u'PRI_jet_subleading_pt',
       u'PRI_jet_subleading_eta', u'PRI_jet_subleading_phi', u'PRI_jet_all_pt',
       u'Weight', u'Label'],
      dtype='object')


In [13]:
#selecting just one row
print (data.iloc[4])

EventId                         100004
DER_mass_MMC                   175.864
DER_mass_transverse_met_lep     16.915
DER_mass_vis                   134.805
DER_pt_h                        16.405
DER_deltaeta_jet_jet                 0
DER_mass_jet_jet                     0
DER_prodeta_jet_jet                  0
DER_deltar_tau_lep               3.891
DER_pt_tot                      16.405
DER_sum_pt                      57.983
DER_pt_ratio_lep_tau             1.056
DER_met_phi_centrality          -1.385
DER_lep_eta_centrality               0
PRI_tau_pt                      28.209
PRI_tau_eta                     -2.197
PRI_tau_phi                     -2.231
PRI_lep_pt                      29.774
PRI_lep_eta                      0.798
PRI_lep_phi                      1.569
PRI_met                          2.723
PRI_met_phi                     -0.871
PRI_met_sumet                   53.131
PRI_jet_num                          0
PRI_jet_leading_pt                   0
PRI_jet_leading_eta      

In [14]:
#first 5 elements
print(data[0:5])

   EventId  DER_mass_MMC  DER_mass_transverse_met_lep  DER_mass_vis  DER_pt_h  \
0   100000       138.470                       51.655        97.827    27.980   
1   100001       160.937                       68.768       103.235    48.146   
2   100002         0.000                      162.172       125.953    35.635   
3   100003       143.905                       81.417        80.943     0.414   
4   100004       175.864                       16.915       134.805    16.405   

   DER_deltaeta_jet_jet  DER_mass_jet_jet  DER_prodeta_jet_jet  \
0                  0.91           124.711                2.666   
1                  0.00             0.000                0.000   
2                  0.00             0.000                0.000   
3                  0.00             0.000                0.000   
4                  0.00             0.000                0.000   

   DER_deltar_tau_lep  DER_pt_tot  ...    PRI_jet_num  PRI_jet_leading_pt  \
0               3.064      41.928  ... 

In [15]:
#Selecting columns
print (data["PRI_jet_leading_eta"])

0       2.150
1       0.725
2       2.053
3       0.000
4       0.000
5      -2.412
6       0.864
7      -0.715
8       0.000
9      -2.767
10      0.000
11     -0.790
12     -0.970
13      0.000
14      0.000
15      0.000
16     -0.766
17      0.000
18      0.000
19      0.000
20      0.000
21      0.000
22      0.000
23      1.156
24      0.000
25      0.000
26      4.347
27     -1.961
28     -0.049
29      0.993
        ...  
4969   -0.284
4970    0.138
4971    0.000
4972   -0.669
4973   -3.640
4974    0.000
4975    1.438
4976   -1.448
4977   -0.199
4978    0.000
4979    0.735
4980    0.000
4981    0.003
4982    0.000
4983   -0.701
4984   -0.980
4985    1.697
4986    2.743
4987   -0.069
4988   -2.662
4989   -1.396
4990    2.131
4991   -1.054
4992   -2.989
4993    0.000
4994    0.000
4995    0.000
4996    0.000
4997   -0.221
4998    1.226
Name: PRI_jet_leading_eta, Length: 4999, dtype: float64


In [16]:
#Or everything at once
data[["Label","PRI_jet_leading_phi","PRI_jet_leading_eta"]][5:10]

Label  PRI_jet_leading_phi  PRI_jet_leading_eta
5     b               -0.653               -2.412
6     s                1.450                0.864
7     s               -1.724               -0.715
8     b                0.000                0.000
9     s               -2.514               -2.767

### Column's basically an array

You can do anything you've done before with arrays - now with actual data.

In [17]:
np.cos(data["PRI_jet_leading_phi"])[:5]

0    0.903041
1    0.401172
2   -0.441441
3    1.000000
4    1.000000
Name: PRI_jet_leading_phi, dtype: float64

In [18]:
phi = data["PRI_jet_leading_phi"]
print ("sin^2(phi) + cos^2(phi) = ",np.sin(phi)**2+np.cos(phi)**2)

sin^2(phi) + cos^2(phi) =  0       1.0
1       1.0
2       1.0
3       1.0
4       1.0
5       1.0
6       1.0
7       1.0
8       1.0
9       1.0
10      1.0
11      1.0
12      1.0
13      1.0
14      1.0
15      1.0
16      1.0
17      1.0
18      1.0
19      1.0
20      1.0
21      1.0
22      1.0
23      1.0
24      1.0
25      1.0
26      1.0
27      1.0
28      1.0
29      1.0
       ... 
4969    1.0
4970    1.0
4971    1.0
4972    1.0
4973    1.0
4974    1.0
4975    1.0
4976    1.0
4977    1.0
4978    1.0
4979    1.0
4980    1.0
4981    1.0
4982    1.0
4983    1.0
4984    1.0
4985    1.0
4986    1.0
4987    1.0
4988    1.0
4989    1.0
4990    1.0
4991    1.0
4992    1.0
4993    1.0
4994    1.0
4995    1.0
4996    1.0
4997    1.0
4998    1.0
Name: PRI_jet_leading_phi, Length: 4999, dtype: float64


### Numpy booleans and indexing

In [19]:
#Logical operations are also elementwise
print ("a==2", a==2)

a==2 [False  True False False False]


In [24]:
print ("Boolean ops")
print ("a = ",a)
print ("b = ",b)

print ("a>2",a>2)                       #suports <, !=, <=, etc.
print ("numpy.logical_not(a>2) = ",     np.logical_not(a>2))
print ("numpy.logical_and(a>2,b>2) = ", np.logical_and(a>2,b>2))
print ("numpy.logical_or(a>4,b<3) = ",  np.logical_or(a>2,b<3))

print ("\nOr simpler")
print ("~(a>2) = ",~(a>2))               #like logical_not
print ("(a>2)&(b>2) = ", (a>2)&(b>2))    #lk logical_and
print ("(a>2)|(b<3) = ", (a>2)|(b<3))    #как logical_or




Boolean ops
a =  [1 2 3 4 5]
b =  [5 4 3 2 1]
a>2 [False False  True  True  True]
numpy.logical_not(a>2) =  [ True  True False False False]
numpy.logical_and(a>2,b>2) =  [False False  True False False]
numpy.logical_or(a>4,b<3) =  [False False  True  True  True]

Or simpler
~(a>2) =  [ True  True False False False]
(a>2)&(b>2) =  [False False  True False False]
(a>2)|(b<3) =  [False False  True  True  True]


In [33]:
print ("\n\nSelecting with booleans")

a = np.array([11,2,3,1,10])

#Selecting elements that match boolean predicate
print ("a = ",a)

print ("a >= 3  =",a>=3)
print ("a[a>=3] =", a[a>=3])
print ("b[a>=3] =", b[a>=3])
print ("numpy.where(a>=3) =",np.where(a>=3)) #indices where mask is True


print ("\nYou can also select elements by their index")
print ("a[[1,3,4]] = ", a[[1,3,4]])
print ("a[[1,2,2,3]] = ", a[[1,2,2,3]])                    #repeat a[2] twice
print ("a[numpy.where(a%2!=0)] = ", a[np.where(a%2!=0)])   #same as a[a%2!=0]



Selecting with booleans
a =  [11  2  3  1 10]
a >= 3  = [ True False  True False  True]
a[a>=3] = [11  3 10]
b[a>=3] = [5 3 1]
numpy.where(a>=3) = (array([0, 2, 4]),)

You can also select elements by their index
a[[1,3,4]] =  [ 2  1 10]
a[[1,2,2,3]] =  [2 3 3 1]
a[numpy.where(a%2!=0)] =  [11  3  1]


### Doing stuff

In [ ]:
#Compute mean and standard deviation of PRI_jet_all_pt
#of only those events where PRI_jet_num equals 2

In [36]:
print('Mean: ', np.mean(data['PRI_jet_all_pt'].where(data['PRI_jet_num']==2)))
print('Std Dev: ', np.std(data['PRI_jet_all_pt'].where(data['PRI_jet_num']==2)))

Mean:  148.290403967
Std Dev:  79.3736166797


In [54]:
#Find the data row with largest PRI_jet_all_pt among those where PRI_jet_num equals 1,
#Print that row
cut = data[data['PRI_jet_num']==1] #selection of all rows where PRI_jet_num =1
max = np.max(cut['PRI_jet_all_pt']) #max value of PRI_jet_all_pt
cut[cut['PRI_jet_all_pt']==max]

EventId  DER_mass_MMC  DER_mass_transverse_met_lep  DER_mass_vis  \
414   100414       123.448                        2.079        46.031   

     DER_pt_h  DER_deltaeta_jet_jet  DER_mass_jet_jet  DER_prodeta_jet_jet  \
414   470.862                   0.0               0.0                  0.0   

     DER_deltar_tau_lep  DER_pt_tot  ...    PRI_jet_num  PRI_jet_leading_pt  \
414               0.532        19.0  ...              1             467.913   

     PRI_jet_leading_eta  PRI_jet_leading_phi  PRI_jet_subleading_pt  \
414               -2.082               -2.722                    0.0   

     PRI_jet_subleading_eta  PRI_jet_subleading_phi  PRI_jet_all_pt    Weight  \
414                     0.0                     0.0         467.913  0.002653   

     Label  
414      s  

[1 rows x 33 columns]

### More numpy

* Full reference aka docs [[here]](https://docs.scipy.org/doc/numpy/reference/)
* Cheat sheet - [[here]](https://pbs.twimg.com/media/C23mQfaWEAAGzBn.jpg)
* Usually you can make your way with tab-ing and shift-tab-ing and following your gut feeling.
 * This is likely not the most efficient way to do so.

In [55]:
#More useful things in numpy:

print("Special numpy array creators:")
print("np.zeros(6) = ",np.zeros(6))
print("np.ones(6) = ",np.ones(6))                 #or you could use np.zeros(7) + 1
print("np.zeros_like(a) = ",np.zeros_like(a))

print("\n")
print("np.arange(5) = ",np.arange(5))
print("np.linspace(0,5,10) = ",np.linspace(0,5,num=11))
print("np.random.normal(0,0.1,10) = ",np.random.normal(0,0.1,size=3)) 


print("Shapes")
v = np.arange(6)
print("v = ",v)
print("np.reshape(v,[2,3]) = \n",np.reshape(v,[2,3]))
print("np.reshape(v,[2,-1]) = \n",np.reshape(v,[2,-1]))   #means "Figure that last dimension out by yourself"

print("np.reshape(v,[10,1]) = \n",np.reshape(v,[6,1]))
print("v[:,None] = \n",v[:,None])

Special numpy array creators:
np.zeros(6) =  [ 0.  0.  0.  0.  0.  0.]
np.ones(6) =  [ 1.  1.  1.  1.  1.  1.]
np.zeros_like(a) =  [0 0 0 0 0]


np.arange(5) =  [0 1 2 3 4]
np.linspace(0,5,10) =  [ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5. ]
np.random.normal(0,0.1,10) =  [-0.12281608  0.08727979 -0.07855873]
Shapes
v =  [0 1 2 3 4 5]
np.reshape(v,[2,3]) = 
 [[0 1 2]
 [3 4 5]]
np.reshape(v,[2,-1]) = 
 [[0 1 2]
 [3 4 5]]
np.reshape(v,[10,1]) = 
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
v[:,None] = 
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [56]:
#Multi-dimensional arrays work exactly as 1d ones, but with more axes
mat = np.reshape(v,[3,2])
print("mat = \n",mat)
print("mat.shape =",mat.shape)
print("mat[2,1] = ",mat[2,1])  #second row, first element, both starting from 0
print("mat[:,0] = ",mat[:,0])  #first column
print("mat[0:2,1] = ",mat[0:2,0])  #two elems of second column


print("\nAxes:")
print("np.sum(mat) = ",np.sum(mat))
print("np.sum(mat,axis=0) = ",np.sum(mat,axis=0))
print("np.sum(mat,axis=1) = ",np.sum(mat,axis=1))


mat = 
 [[0 1]
 [2 3]
 [4 5]]
mat.shape = (3, 2)
mat[2,1] =  5
mat[:,0] =  [0 2 4]
mat[0:2,1] =  [0 2]

Axes:
np.sum(mat) =  15
np.sum(mat,axis=0) =  [6 9]
np.sum(mat,axis=1) =  [1 5 9]


In [57]:
print("A glimpse into broadcasting")
print("np.reshape(v,[6,1]) + np.reshape(v,[1,6]) = \n",np.reshape(v,[6,1]) + np.reshape(v,[1,6]))

A glimpse into broadcasting
np.reshape(v,[6,1]) + np.reshape(v,[1,6]) = 
 [[ 0  1  2  3  4  5]
 [ 1  2  3  4  5  6]
 [ 2  3  4  5  6  7]
 [ 3  4  5  6  7  8]
 [ 4  5  6  7  8  9]
 [ 5  6  7  8  9 10]]


In [58]:
#In short, you can divide(elem-wise) matrix by a row vector 
#or perform any operation when two arrays share last axes
print("matrix shape =",mat.shape)
print("vector shape =",np.mean(mat,axis=0).shape)
print("Result:")

print(mat / np.mean(mat,axis=0))



matrix shape = (3, 2)
vector shape = (2,)
Result:
[[ 0.          0.33333333]
 [ 1.          1.        ]
 [ 2.          1.66666667]]


In [ ]:
#So for example, you can't divide matrix by a column vector...

print("matrix shape =",mat.shape)
print("vector shape =",np.mean(mat,axis=1).shape)
print("Result:")

print(mat / np.mean(mat,axis=1))

In [ ]:
#... but you can replace vector with a single-column matrix 
# because the final axis is gonna be broadcasted

print("matrix shape =",mat.shape)
print("vector shape =",np.mean(mat,axis=1).reshape([3,1]).shape)
print("Result:")

mat / np.mean(mat,axis=1).reshape([3,1])

# The quest

In [ ]:
matrix = data[["DER_mass_MMC","DER_mass_transverse_met_lep","DER_mass_vis","DER_pt_h"]].values
matrix

__Normalize the matrix:__ subtract from each column its mean and divide by the standard deviation. 

I suggest np.mean, np.std with axis parameter.

In [ ]:
matrix_normalized = <your code>

In [ ]:
print("Sanity check, print new mean and new std for each column")
<your code>

Print for the following matrix row numbers for those rows, where row sum is greater than 1. 
I suggest np.sum and np.where.

In [ ]:
<your code>

```

```
```

```
```

```
```

```
```

```
```

```
```

```
```

```
```

```
```

```
```

```
```

```
```

```


## Performance stuff: "how fast is it, Harry?"
![img](http://statics.viralizalo.com/virs/2016/02/VIR_155188_11939_harry_potter_y_el_prisionero_de_azkaban_test_solo_para_fans.jpg?cb=383)


Let's see if numpy is any faster than loops

* Doing some elementwise ops
* Three options
 * Pure python
 * Start python, convert to numpy
 * Pure numpy



In [ ]:
%%time
#This cell magic prints the time it took to run the cell


#Pure python

arr_1 = range(1000000)
arr_2 = range(99,1000099)


a_sum = []
a_prod = []
sqrt_a1 = []

#elementwise sum/prod/sqrt
for i in range(len(arr_1)):
    a_sum.append(arr_1[i]+arr_2[i])
    a_prod.append(arr_1[i]*arr_2[i])
    a_sum.append(arr_1[i]**0.5)
    
#sum of all elements of arr_1
arr_1_sum = sum(arr_1)


In [ ]:
%%time

#start with list, convert to numpy
arr_1 = range(1000000)
arr_2 = range(99,1000099)

arr_1, arr_2 = np.array(arr_1) , np.array(arr_2)


a_sum = arr_1 + arr_2
a_prod = arr_1*arr_2
sqrt_a1 = arr_1**.5

np.sum(arr_1)


In [ ]:
%%time

# Pure numpy
arr_1 = np.arange(1000000)
arr_2 = np.arange(99,1000099)

a_sum = arr_1 + arr_2
a_prod = arr_1*arr_2
sqrt_a1 = arr_1**.5

np.sum(arr_1)


```

```
```

```
```

```
```

```
```

```
```

```
```

```
```

```
```

```
```

```
```

```
```

```
```

```


# Matplotlib

Simple and powerful plotting to make sense of data.

![img](https://imgs.xkcd.com/comics/extrapolating.png)


In [ ]:
import matplotlib.pyplot as plt
#VV This is an official "magic" to force plots inside your notebook
%matplotlib inline                

#line plot
plt.plot([0,1,2,3,4,5],[0,1,4,9,16,25])

In [ ]:
#line plot with better formatting

plt.title("Super-plot")

plt.xlabel("Number of layers")
plt.ylabel("Coolness")

plt.plot([0,1,2,3,4,5],[0,1,4,9,16,25],marker='o',label='super-curve')

plt.legend(loc='best')
plt.grid()

In [ ]:
#scatter-plot

#draw first plot
plt.scatter(np.arange(10),np.arange(10)**2)     #just to show that np-arrays are allowed

#Show it, start new plot
plt.show()

#Draw two scatters in one plot
plt.scatter([1,1,2,3],[10,12,6,20],c = ["red","blue","blue","green"],marker = "x")
plt.scatter([0,1,2,3,4,5],[0,1,4,9,16,25],c = "black")


In [ ]:
#Histogram
plt.hist([0,1,1,1,2,2,3,3,3,3,3,4,4,5,5,5,6,7,7,8,9,10])
plt.show()


plt.hist([0,1,1,1,2,2,3,3,3,3,3,4,4,5,5,5,6,7,7,8,9,10],bins = 5) 


#now gently press shift+tab+tab with cursor inside plt.hist  -^^

In [ ]:
#plot a histogram of PRI_jet_leading_pt

<your code>

#bonus: separate histograms for PRI_jet_leading_pt where PRI_jet_num equals 0,1,2 and 3 respectively


In [ ]:
#make a scatter-plot of DER_mass_MMC vs DER_mass_jet_jet

<your code here>

#bonus: make it as clear as possible with formatting

### More matplotlib

* Docs - [[url]](https://matplotlib.org/2.0.2/contents.html)
* Cheat sheet - [[url]](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Python_Matplotlib_Cheat_Sheet.pdf)
* Examples - [[url]](https://matplotlib.org/examples/)

In [ ]:
#Final boss - find a way to display a 2-dimensional histogram 
#of DER_mass_MMC vs DER_mass_jet_jet

```

```
```

```
```

```
```

```
```

```
```

```
```

```
```

```
```

```
```

```
```

```
```

```
```

```

<center>You made it!</center>

![img](https://pbs.twimg.com/media/CrHblh9WgAEoH1u.jpg)